# Database (Local)
spring.datasource.url=jdbc:postgresql://localhost:5432/salutis_dev
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT (Dev - not for production)
jwt.secret=thisisasecuredevjwtkeywith32bytesforhmacsha256testing12345
jwt.expiration=86400000

# App
spring.application.name=Salutis-Dev
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.backend=DEBUG
logging.level.org.springframework.security=DEBUG
